

services:
  musichub:
    image: eianz/musichub:latest
    container_name: musichub
    restart: unless-stopped
    ports:
      # 宿主机:容器
      - "5173:5173"
    volumes:
      # 音乐输出目录（宿主机相对路径 ./music）
      - ./music:/music
      # 配置/数据库/Cookie 目录
      - ./config:/config
